#!/bin/zsh -f
# Usage: coffeetrack [what] [where]

what=${1:-coffee}
where=${2:-saltside}

logfile=$HOME/.coffee.log

case $(hostname) in
	neptune)
		where='saltside'
		;;

	banana|plum|peach*)
		where='home'
		;;
esac

echo $(date +%FT%H:%M:%S%z) $where $what >> $logfile
