#!/usr/bin/env sh
# Keep track of when I'm doing stuff, like drinking coffee, and where I'm
# doing it.
#
# Usage: coffeetrack [what]
#
# Where 'what' is just a word, like coffee or pushups.

# Default values.
WHAT='coffee'
WHERE='qualisys'
LOGFILE=$HOME/.coffee.log

case `hostname` in
	labbusers*) WHERE='qualisys' ;;
	banana|plum|peach*) WHERE='home' ;;
esac

[ x$1 != x ] && WHAT=$1

echo `date +%FT%H:%M:%S%z` $WHERE $WHAT >> $LOGFILE
