#!/bin/zsh -f

highlight() {
	local color=$1
	echo '\x1b[1m\x1b[38;5;'${color}'m'
}

reset='\x1b[0m'

info=68
warning=214
error=196
critical=128
debug=36

sed "s#WARN\(ING\)*\b#$(highlight $warning)&${reset}#i; \
	s#ERR\(OR\)*\b#$(highlight $error)&${reset}#i; \
	s#INF\(O\)*\b#$(highlight $info)&${reset}#i; \
	s#DEBUG\b#$(highlight $debug)&${reset}#i; \
	s#CRIT\(ICAL\)*\b#$(highlight $critical)&${reset}#i; "
