#!/usr/bin/env ruby

palette = %w{FE4365 FC9D9A F9CDAD C8C8A9 83AF9B}

commits = {}
commits.default = 0

`git log --date=short --pretty=format:%cd`.lines do |line|
	commits[line.strip] += 1
end

url = "http://chart.apis.google.com/chart?" +
	"cht=bvs&chbh=a&chs=%dx%d&chco=%s&chd=t:" %
	[[1000, 25 * commits.size].min, 150, palette.join("|")]

url += commits.sort_by{|k,v| k}.map{|_,c| c.to_s}.join(",")
url += "&chds=%d,%d" %
	[0, commits.values.max]

case RUBY_PLATFORM
when /linux/
	`xdg-open "#{url}"`
when /darwin/
	`open "#{url}"`
else
	puts url
end
