#!/bin/zsh -f
# Run a command until it returns a successful exit value.

try=0
sound=false

while [[ ${#@} -gt 0 ]]; do
	arg=$1
	shift 1

	case $arg in
		--) break ;;
		-s) sound=true ;;
	esac
done

command_=$@

if [[ -z $command_ ]]; then
	echo "usage: insist [-s] -- command"
	exit 1
fi

function play() {
	local file=$1
	$sound && aplay -q -D 'pulse' $file &!
}

function fail() {
	printf "[Failed attempt $try]\n"
	mplayer -really-quiet "/home/majoh/media/sound/Sad Trombone Sound Effect - FAIL Sound - Fail Horns.mp3" &!
}

function success() {
	printf "[Success after $try attempts]\n"
	[[ $try -gt 0 ]] \
		&& mplayer -really-quiet "/home/majoh/media/sound/Stadium Applause 1 Sound Effect.mp3" &!
}

function wait() {
	local retries=$1
	local wait=$[1.3 ** retries]
	printf "[Waiting %0.2f seconds before next try]\n" $wait
	sleep $wait
}

while true; do
	eval $command_

	case $? in
		0) success; exit 0 ;;
		127)
			fail
			echo "Command not found" >&2
			exit 127
			;;
		*) fail ;;
	esac

	try=$[try+1]
	wait $try
done
