#!/bin/zsh -f

app_token=$PUSHOVER_APP_TOKEN
user_token=$PUSHOVER_USER_TOKEN

args=()

for arg in $@; do
	if [[ $arg =~ --.+=.+ ]]; then
		args+="-F"
		args+=${(q)arg/--/}
		shift 1
	else
		break
	fi
done

text="${@:-$(cat)}"

curl -X POST https://api.pushover.net/1/messages.json \
	-F "token=$app_token" \
	-F "user=$user_token" \
	$args \
	-F "message=$text"
