#!/bin/sh

TIMESPEC=seconds
ST=`TZ=Europe/Stockholm     date --rfc-3339=$TIMESPEC`
LK=`TZ=Asia/Sri_Lanka       date --rfc-3339=$TIMESPEC`
GH=`TZ=Africa/Ghana         date --rfc-3339=$TIMESPEC`
BD=`TZ=BST                  date --rfc-3339=$TIMESPEC`
UT=`TZ=UTC                  date -u --rfc-3339=$TIMESPEC`

echo "       Ghana $GH"
echo "   Stockholm $ST"
echo "   Sri Lanka $LK"
echo "  Bangladesh $BD"
echo "         UTC $UT"
