#!/bin/sh

TIMESPEC=seconds
AT=`TZ=Australia/Sydney date --rfc-3339=$TIMESPEC`
ET=`TZ=US/Eastern       date --rfc-3339=$TIMESPEC`
PT=`TZ=US/Pacific       date --rfc-3339=$TIMESPEC`
ST=`TZ=Europe/Stockholm date --rfc-3339=$TIMESPEC`

echo "   Stockholm $ST"
echo " Los Angeles $PT"
echo "    New York $ET"
echo "   Melbourne $AT"
