#!/bin/sh

TIMESPEC=seconds
FORMAT="%Y-%m-%d %H:%S:%M %Z"
AT=`TZ=Australia/Sydney date +"$FORMAT"`
ET=`TZ=US/Eastern       date +"$FORMAT"`
PT=`TZ=US/Pacific       date +"$FORMAT"`
ST=`TZ=Europe/Stockholm date +"$FORMAT"`

echo "   Stockholm $ST"
echo " Los Angeles $PT"
echo "    New York $ET"
echo "   Melbourne $AT"
